vich_uploader:
    db_driver: orm

    mappings:
        trick_media:
            uri_prefix: '%trick_media%'
            upload_destination: '%kernel.project_dir%/public/%trick_media%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false

    metadata:
        type: 'attribute'