vich_uploader:
    db_driver: orm

    metadata:
        type: 'attribute'

    mappings:
        trick_main_picture:
            uri_prefix: '%trick_main_picture%'
            upload_destination: '%kernel.project_dir%/public/%trick_main_picture%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false

        trick_media_picture:
            uri_prefix: '%trick_media_picture%'
            upload_destination: '%kernel.project_dir%/public/%trick_media_picture%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false

        trick_media_video:
            uri_prefix: '%trick_media_video%'
            upload_destination: '%kernel.project_dir%/public/%trick_media_video%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false