version: '3'

services:
  database:
    image: mysql:latest
    container_name: db_snow_tricks
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'snow_tricks'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'adminiscoming'
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_snow_tricks
    depends_on:
      - database
    environment:
      PMA_HOST: database
    ports:
      - 8080:80
    volumes:
      - ./data/phpmyadmin:/var/lib/phpmyadmin

  maildev:
    image: maildev/maildev:latest
    container_name: maildev_snow_tricks
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - '8081:80'
      - '25:25'
